### PR TITLE
Change the method of adding keys from directly modifying files to using the command "tizen security-profiles add".

### PR DESCRIPTION
**Pull request by yakira-neko**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
At the moment peeking this I'm quite nervous. It seems to completely rework the action removing inputs and changing the output. Did you mean to open this upstream?

**Comment by yakira-neko** [comment]
Yes, indeed. I found the original version to be flawed. Despite inputting all the necessary content, I encountered issues such as being prompted with a password error despite entering the correct one and facing difficulties installing the generated build files onto my device. Therefore, I meticulously revised the build script based on the Tizen CLI documentation to ensure seamless functionality.

**Review by iBotPeaches — CHANGES_REQUESTED** [review]
Apologies you had some struggles with this. At the moment I am going to put this on hold for merging while we investigate further your changes here. They seem overwhelming at quick glance with a completely reworked parameter set.

**Comment by iBotPeaches** [comment]
Not moving forward with this at this time.

**Pull request closed without merging**
